# Generated by Django 4.2.6 on 2023-10-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_alter_author_is_staff_alter_author_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profileImage',
        ),
    ]
