# Generated by Django 4.2.6 on 2023-10-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
