# Generated by Django 4.2.6 on 2023-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_alter_author_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
