# Generated by Django 4.2.6 on 2023-11-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_author_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='Author', editable=False, max_length=200),
        ),
    ]
