# Generated by Django 4.2.6 on 2023-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0022_author_following_author_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='type',
            field=models.CharField(default='Friend_Request', editable=False, max_length=200),
        ),
    ]
