# Generated by Django 4.2.6 on 2023-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0028_alter_friendrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='origin',
            field=models.TextField(default='', max_length=255),
        ),
    ]
