# Generated by Django 4.2.6 on 2023-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0029_author_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='origin',
            field=models.TextField(default='', max_length=255),
        ),
    ]
