# Generated by Django 4.2.6 on 2023-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0032_alter_author_origin_alter_friendrequest_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foreign_authors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
