# Generated by Django 4.2.6 on 2023-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0034_author_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
    ]
