# Generated by Django 4.2.6 on 2023-12-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0035_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id2',
            field=models.TextField(editable=False, null=True),
        ),
    ]
