# Generated by Django 4.2.6 on 2023-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0036_alter_author_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='id2',
            field=models.TextField(editable=False, null=True),
        ),
    ]
