# Generated by Django 4.2.6 on 2023-10-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='description',
            field=models.TextField(),
        ),
    ]
