# Generated by Django 4.2.6 on 2023-10-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_alter_apppost_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='categories',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='origin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=255),
        ),
    ]
