# Generated by Django 4.2.6 on 2023-10-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_my_posts'),
        ('likes', '0001_initial'),
        ('app_posts', '0006_apppost_comment_count_alter_apppost_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppost',
            name='liked',
            field=models.ManyToManyField(editable=False, to='likes.like'),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='origin',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='source',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='unlisted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
