# Generated by Django 4.2.6 on 2023-10-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_my_posts'),
        ('app_posts', '0007_apppost_liked_alter_apppost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
