# Generated by Django 4.2.6 on 2023-10-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_my_posts'),
        ('app_posts', '0008_alter_apppost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppost',
            options={'ordering': ['published']},
        ),
        migrations.AlterField(
            model_name='apppost',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
