# Generated by Django 4.2.6 on 2023-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0009_alter_apppost_options_alter_apppost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='contentType',
            field=models.CharField(blank=True, default='text/plain', max_length=255),
        ),
    ]
