# Generated by Django 4.2.6 on 2023-10-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0011_alter_apppost_contenttype_alter_apppost_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppost',
            name='contentMarkdown',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='apppost',
            name='contentPlain',
            field=models.TextField(default='', editable=False),
        ),
    ]
