# Generated by Django 4.2.6 on 2023-11-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0023_alter_apppost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
