# Generated by Django 4.2.6 on 2023-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_like_object_type'),
        ('app_posts', '0028_alter_apppost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='liked',
            field=models.ManyToManyField(to='likes.like'),
        ),
    ]
