# Generated by Django 4.2.6 on 2023-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0029_alter_apppost_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
