# Generated by Django 4.2.6 on 2023-11-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0030_alter_apppost_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
