# Generated by Django 4.2.6 on 2023-11-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0030_alter_apppost_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='origin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
