# Generated by Django 4.2.6 on 2023-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0031_alter_apppost_origin_alter_apppost_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='origin',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='source',
            field=models.TextField(default='', max_length=255),
        ),
    ]
