# Generated by Django 4.2.6 on 2023-11-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0031_apppost_image'),
        ('app_posts', '0033_alter_apppost_origin_alter_apppost_source'),
    ]

    operations = [
    ]
