# Generated by Django 4.2.6 on 2023-11-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0031_apppost_image'),
        ('app_posts', '0034_rename_comment_count_apppost_count_apppost_comments'),
    ]

    operations = [
    ]
