# Generated by Django 4.2.6 on 2023-11-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0034_merge_20231126_2137'),
        ('app_posts', '0035_merge_20231127_0554'),
    ]

    operations = [
    ]
