# Generated by Django 4.2.6 on 2023-12-02 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_posts', '0036_merge_20231127_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppost',
            name='friends_to_notify',
            field=models.ManyToManyField(blank=True, related_name='private_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
