# Generated by Django 4.2.6 on 2023-10-27 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0005_alter_apppost_categories_alter_apppost_content_and_more'),
        ('likes', '0001_initial'),
        ('authors', '0005_author_my_posts'),
        ('comments', '0002_comment_created_time_comment_post_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='authors.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.TextField(default='text/plain'),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(editable=False, to='likes.like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app_posts.apppost'),
        ),
    ]
