# Generated by Django 4.2.6 on 2023-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_like_object_type'),
        ('comments', '0006_alter_comment_options_comment_contentmarkdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(to='likes.like'),
        ),
    ]
