# Generated by Django 4.2.6 on 2023-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_alter_comment_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
