# Generated by Django 4.2.6 on 2023-11-13 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='summary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
