# Generated by Django 4.2.6 on 2023-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_like_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
