# Generated by Django 4.2.6 on 2023-12-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0008_like_id2_alter_like_id_alter_like_object_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id2',
            field=models.TextField(editable=False, null=True),
        ),
    ]
