# Generated by Django 4.2.6 on 2023-12-05 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_alter_like_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
