# Generated by Django 4.2.6 on 2023-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='Inbox', editable=False, max_length=200),
        ),
    ]
