# Generated by Django 4.2.6 on 2023-11-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0022_author_following_author_friends_friendrequest'),
        ('inboxes', '0002_inbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='authors.friendrequest'),
        ),
    ]
