# Generated by Django 4.2.6 on 2023-11-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0003_alter_inbox_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='posts',
        ),
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='friend_requests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
